---
title: "w13"
author: "fg"
date: "25/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Libraries

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(lubridate)
library(scales)
library(DT)
library(unvotes)
library(tidytuesdayR)



library(showtext)
font_add_google("Roboto", "roboto")
font_add_google("Roboto Condensed", "roboto condensed")
font_add_google("Press Start 2P", "start2p")
font_add_google("Share Tech Mono", "techmono")
showtext_opts(dpi = 320)
showtext_auto(enable = FALSE)



#^showtext_auto(enable = TRUE)
library(patchwork)
library(sf)
library(ggplot2)
library(rnaturalearth)
library(magick)
library(grid)

library(png)
```


Set the colors
```{r}
palette <- c("ocra" = "#F7BB0B", 
             "lilla" = "#C88BD9", 
             "turchese" = "#49B3BF", 
             "verdino" = "#94BF75", 
             "strong_orange" = "#FD5403", 
             "antracite" = "#2e2e2e")


title_clr <- "#94BCFF" #celestino


bck_clr <- "grey20"


#bck_color <- "#FEFCEF" #panna
```



Get data

```{r message=FALSE, warning=FALSE}
unvotes <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-03-23/unvotes.csv')
roll_calls <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-03-23/roll_calls.csv')
issues <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-03-23/issues.csv')
```




unvotes_full and unvotes_sub

```{r}
unvotes_full <- unvotes %>%
 inner_join(un_roll_calls, by = "rcid") %>%
 inner_join(un_roll_call_issues, by = "rcid")

unvotes_sub  <- unvotes_full%>%
 select(date,country,session,vote,issue)
```



unvotes_merged_country_names

```{r}
german<-unvotes_full%>%filter(str_detect(country, "Germ"))
#table(german$country)
congo<-unvotes_full%>%filter(str_detect(country, "Congo"))
#table(congo$country)
yemen<-unvotes_full%>%filter(str_detect(country, "Yemen"))
#table(yemen$country)
guinea<-unvotes_full%>%filter(str_detect(country, "Guinea"))
#table(guinea$country)


unvotes_merged_country_names<-unvotes_sub%>%
mutate(country=case_when(country=="Federal Republic of Germany"~"Germany",
country=="German Democratic Republic"~"Germany",
country=="Congo - Brazzaville"~"Congo",
country=="Congo - Kinshasa"~"Congo",
country=="Micronesia (Federated States of)"~"Micronesia",
country=="Myanmar (Burma)"~"Myanmar",
country=="Yemen Arab Republic"~"Yemen",
country=="Yemen People's Republic"~"Yemen",
country=="Guinea-Bissau"~"Giunea",
TRUE~country))%>%
select(date,country,vote,issue) %>%
arrange(date)
```


by_country_year

```{r message=FALSE, warning=FALSE}
by_country_year <- unvotes_merged_country_names %>%

  group_by(year = year(date), country) %>%
  
  summarize(issue,votes = n(),
            
  percent_yes = round(mean(vote == "yes")*100,1),
  percent_no = round(mean(vote == "no")*100,1),
  percent_astain = round(mean(vote == "abstain")*100,1))
```


vote_yr and vote_yr_select_countries

```{r message=FALSE, warning=FALSE}
vote_yr<-unvotes_merged_country_names %>%
filter(country != c("Italy", "Haiti", "Mexico")) %>%
mutate(year = year(date)) %>%
group_by(country, year, issue) %>%
summarize(percent_yes = mean(vote == "yes"))%>%
filter(issue=="Human rights")

vote_yr_select_countries<-unvotes_merged_country_names %>%
filter(country %in% c("Italy", "Haiti", "Mexico")) %>%
mutate(year = year(date)) %>%
group_by(country, year, issue) %>%
summarize(percent_yes = mean(vote == "yes"))%>%
filter(issue=="Human rights")
```



Issue plot

```{r}
issues_plot<-ggplot() +

  geom_bar(data=unvotes_sub,aes(x = vote,fill = issue,color=vote) )+

  scale_fill_hue() +

  theme_void() +
  theme(legend.position = "none")+
 
facet_wrap(vars(issue))


```


Yes proportions plot

```{r}
linechart<- ggplot() +
  geom_smooth(data=vote_yr,
             mapping=aes(x = year, y = percent_yes,group=country),color="grey80",
             size=0.3,method = "glm", se = FALSE,)+

  geom_smooth(data=vote_yr_select_countries,
             mapping=aes(x = year, y = percent_yes,color=country),
             size=0.8,method = "loess", se = F)+
   geom_jitter(data=vote_yr_select_countries,
               aes(x = year, y = percent_yes,color=country),
               height = 0.2)+ 
  
   
#facet_wrap(~issue)+



  theme_void()+
scale_y_continuous(labels = scales::percent)+
theme(legend.position = "top")
#scale_x_continuous(label=seq(1946,2019,by=30))
```


Votes trend plot

```{r}
main_plot<-ggplot(data=by_country_year)+
  geom_line(aes(x=year,y=votes))+
  
  theme_bw()
  #scale_x_continuous(breaks = 10)
  
```

```{r}
mean_votes<-by_country_year%>%group_by(country,issue)%>%summarize(mean_votes=mean(votes))
```
```{r}
Human_rights<- by_country_year%>%group_by(country,issue)%>%summarize(mean_votes=mean(votes))%>%filter(issue=="Human rights")
```

```{r}
Human_rights%>%arrange(mean_votes)
```

```{r}
eco_dev<-by_country_year%>%group_by(country,issue)%>%summarize(tot_votes=sum(votes))%>%
  arrange(tot_votes)%>%filter(issue=="Economic development")%>%
  arrange(desc(tot_votes))
```


```{r}
by_country_year%>%DT::datatable()
```


```{r}
tot_votes<-by_country_year%>%group_by(country,issue)%>%summarize(tot_votes=sum(votes))%>%
  arrange(tot_votes)%>%arrange(issue)%>%
DT::datatable()

```



```{r}
ggplot(data=tot_votes)+
  geom_boxplot(aes(x=issue,y=tot_votes))+
  coord_flip()
```


```{r}
a<-unvotes_merged_country_names%>%filter(vote=="yes",country=="Italy",issue=="Human rights")%>%
  group_by(year=year(date))%>%
  summarize(year,votes=n(),vote)
b<-unvotes_merged_country_names%>%filter(vote=="no",country=="Italy",issue=="Human rights")%>%
  group_by(year=year(date))%>%
  summarize(year,votes=n(),vote)
c<-unvotes_merged_country_names%>%filter(vote=="abstain",country=="Italy",issue=="Human rights")%>%
  group_by(year=year(date))%>%
  summarize(year,votes=n(),vote)
  


```
```{r}
par(mfrow=c(1,3))
plot(a$votes~a$year,type="o")
plot(b$votes~b$year,col="red",type="o")
plot(c$votes~c$year,col="blue",type="o")
```
```{r}

```



```{r}
plot(Human_rights$`mean(votes)`,type="l")
```







```{r message=FALSE, warning=FALSE}
library(ggimage)

UN_img="https://camo.githubusercontent.com/654fb54c78403255bbe1457b6a75423f5e370ee075eab4db0a189b886b68b8d7/68747470733a2f2f75706c6f61642e77696b696d656469612e6f72672f77696b6970656469612f636f6d6d6f6e732f7468756d622f652f65652f554e5f656d626c656d5f626c75652e7376672f3132303570782d554e5f656d626c656d5f626c75652e706e67"

tidy_logo<-image_read("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/static/plot_logo.png") %>% 
  image_resize("300x300")


g1<-ggbackground(linechart, UN_img, alpha=.4, color="#94BCFF")

g2<-ggbackground(main_plot, UN_img, alpha=.7,color="#94BCFF") 

g3<-ggbackground(issues_plot, UN_img,alpha=.9,color="#94BCFF") 


all<-cowplot::plot_grid(g1, g2, g3, ncol=3)



final<- all+
  plot_annotation(
    
     
     title = "UN Votes from 1946 to 2019", 
     subtitle = "Voting between 1946 and 2019",
     caption = "Visualization: Federica Gazzelloni | Data: UN votes",
      
     
     theme = theme(
       
       plot.title = element_text(vjust = 2,              # adjust vertical title position
                                  hjust = -0.735,        # adjust horizontal title position
                                  size = 20,             # make title text bigger
                                  face = "bold"),
       
       plot.subtitle = element_text(vjust = 2,           # adjust vertical subtitle position
                                     hjust = -1.19,       # adjust horizontal subtitle position
                                     size = 12),
                                 
                                 
        plot.margin = margin(10,10,10,10),
        plot.background = element_rect(fill = bck_clr, color = NA),
        plot.caption = element_text(family = "techmono", 
                                    size = 9, color = "white", 
                                    margin = margin(15,0,0,0), hjust = 0.95)))      
   




```







```{r}

final <- all + 
  #inset_element(img_logo, -1,1,1206.02,1207.02) +
  plot_annotation(
    caption = "Visualization: Federica Gazzelloni | Data: UN votes",
    
   title = "UN Votes from 1946 to 2019",
    
   theme = theme(
      plot.margin = margin(10,10,10,10),
      plot.background = element_rect(fill = bck_clr, color = NA),
      plot.caption = element_text(family = "techmono", size = 9, color = "white", margin = margin(15,0,0,0), hjust = 0.95)      
    )
  )


  annotation_custom(textGrob("Footer goes here", gp=gpar(col="blue")), 
                    xmin=100, 
                    xmax=100, 
                    ymin=0.6*1946, 
                    ymax=0.6*1946) +
  theme(plot.margin=margin(5,5,30,5))



ragg::agg_png(here::here("render", paste0("UN_votes_", 
                                          format(Sys.time(), 
                                                 "%Y%m%d_%H%M%S"), 
                                          ".png")), 
              res = 320, width = 14, height = 8, units = "in")
final
  
dev.off()
```



Read the image, attach the Tidytuesday logo and save it

```{r}
UN_votes_plot <- image_read(here("render", paste0("UN_votes_", 
                                          format(Sys.time(), 
                                                 "%Y%m%d_%H%M%S"), 
                                          ".png")))
                            


attached_logo <- image_composite(UN_votes_plot, un_logo, 
                       offset = "+2650+35") # tell R where to put the logo

image_write(attached_logo, path = "~/R/Projects/TidyTuesday/render/UN_votes_W13.png", format = "png") # save final plot
```



